# Generated by Django 4.2.2 on 2023-06-24 02:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id_funcionario', models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11)),
                ('data_nascimento', models.DateField()),
                ('endereco', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('matricula', models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('categoria', models.CharField(choices=[('A', 'Aluno'), ('P', 'Piloto'), ('I', 'Instrutor')], max_length=9)),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11)),
                ('data_nascimento', models.DateField()),
                ('endereco', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, validators=[django.core.validators.EmailValidator()])),
                ('nota_ponderada', models.FloatField(null=True)),
                ('breve', models.CharField(max_length=100, null=True)),
                ('nome_do_curso', models.CharField(max_length=100, null=True)),
                ('data_diploma', models.DateField(null=True)),
                ('instituicao_diploma', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Voo',
            fields=[
                ('id_voo', models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('horario_saida', models.TimeField()),
                ('horario_chegada', models.TimeField()),
                ('parecer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('id_instrutor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='instrutor_voo', to='av_system.socio')),
                ('id_socio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='socio_voo', to='av_system.socio')),
            ],
            options={
                'ordering': ['data', 'horario_saida'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=300)),
                ('id_funcionario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='av_system.funcionario')),
                ('id_socio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='av_system.socio')),
            ],
        ),
        migrations.AddIndex(
            model_name='funcionario',
            index=models.Index(fields=['id_funcionario'], name='av_system_f_id_func_d99034_idx'),
        ),
        migrations.AddIndex(
            model_name='voo',
            index=models.Index(fields=['id_voo'], name='av_system_v_id_voo_ed3cce_idx'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['id_usuario'], name='av_system_u_id_usua_725883_idx'),
        ),
    ]
