# Generated by Django 4.2.2 on 2023-06-28 16:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('data_nascimento', models.DateField()),
                ('endereco', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('A', 'Aluno'), ('P', 'Piloto'), ('I', 'Instrutor')], max_length=9)),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11)),
                ('data_nascimento', models.DateField()),
                ('endereco', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, validators=[django.core.validators.EmailValidator()])),
                ('breve', models.CharField(max_length=100, null=True)),
                ('nome_do_curso', models.CharField(max_length=100, null=True)),
                ('data_diploma', models.DateField(null=True)),
                ('instituicao_diploma', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Voo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('horario_saida', models.TimeField()),
                ('horario_chegada', models.TimeField()),
                ('parecer', models.CharField(choices=[('A', 4.0), ('B', 3.0), ('C', 2.0), ('D', 1.0)], max_length=1)),
                ('id_instrutor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='instrutor_voo', to='av_system.socio')),
                ('id_socio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='socio_voo', to='av_system.socio')),
            ],
            options={
                'ordering': ['data', 'horario_saida'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('is_funcionario', models.BooleanField(default=False)),
                ('is_socio', models.BooleanField(default=False)),
                ('is_aluno', models.BooleanField(default=False)),
                ('is_instrutor', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='usuario_set', related_query_name='usuario', to='auth.group', verbose_name='groups')),
                ('id_funcionario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='av_system.funcionario')),
                ('matricula', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='av_system.socio')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='usuario_set', related_query_name='usuario', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'permissions': (('funcionario', 'Funcoes administrativas'), ('socio', 'Apenas consulta de voos'), ('aluno', 'Consulta de voos e requerimento de breve'), ('instrutor', 'Cadastro e consulta de voos')),
            },
        ),
        migrations.AddIndex(
            model_name='socio',
            index=models.Index(fields=['id'], name='av_system_s_id_4aa01b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='socio',
            unique_together={('cpf', 'categoria')},
        ),
        migrations.AddIndex(
            model_name='funcionario',
            index=models.Index(fields=['id'], name='av_system_f_id_646448_idx'),
        ),
        migrations.AddIndex(
            model_name='voo',
            index=models.Index(fields=['id'], name='av_system_v_id_d52146_idx'),
        ),
    ]
