# Generated by Django 4.2.2 on 2023-06-24 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('av_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cpf',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='voo',
            name='parecer',
            field=models.CharField(choices=[('A', 5), ('B', 4), ('C', 3), ('D', 2)], max_length=1),
        ),
        migrations.AlterUniqueTogether(
            name='socio',
            unique_together={('cpf', 'categoria')},
        ),
        migrations.AddIndex(
            model_name='socio',
            index=models.Index(fields=['matricula'], name='av_system_s_matricu_309797_idx'),
        ),
    ]
