# Generated by Django 4.2.2 on 2023-06-28 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('av_system', '0001_initial'),
    ]

    operations = [
    ]
