# Generated by Django 4.2.2 on 2023-06-24 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('av_system', '0002_alter_funcionario_cpf_alter_voo_parecer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='id_socio',
            new_name='matricula',
        ),
    ]
